name: interapas_gen_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  dotted_border: ^2.1.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  text_scroll: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/logo.png
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat_Medium
      fonts:
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat_Bold
      fonts:
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
