name: interapas_gen_app
description: "Aplicación de uso general para los trabajadores de Interapas."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  collection: ^1.18.0
  dotted_border: ^2.1.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  http_parser: ^4.0.2
  image_watermark: ^0.1.0
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  text_scroll: ^0.2.0
  watermark_unique: ^1.0.7

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/logo.png
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat_Medium
      fonts:
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat_Bold
      fonts:
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
