name: interapas_gen_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  http: ^1.2.1
  package_info_plus: ^8.0.0
  path: ^1.9.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/logo.png
    